longhorn:
  image:
    pullPolicy: Always
  service:
    ui:
      type: NodePort
    manager:
      type: NodePort
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    storageMinimalAvailablePercentage: 10
