# https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml
longhorn:
  ui:
    type: NodePort
  manager:
    type: NodePort
  persistence:
    defaultClassReplicaCount: 2
  defaultSettings:
    storageMinimalAvailablePercentage: 10
