nextcloud:
  nextcloud:
    host: nextcloud.dti.ctex.eb.mil.br
  mariadb:
    enabled: true
  redis:
    enabled: true
  ## Allowing use of ingress controllers
  ## ref: https://kubernetes.io/docs/concepts/services-networking/ingress/
  ##
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: traefik
    #  nginx.ingress.kubernetes.io/proxy-body-size: 4G
    #  kubernetes.io/tls-acme: "true"
    #  cert-manager.io/cluster-issuer: letsencrypt-prod
    #  nginx.ingress.kubernetes.io/server-snippet: |-
    #    server_tokens off;
    #    proxy_hide_header X-Powered-By;

    #    rewrite ^/.well-known/webfinger /public.php?service=webfinger last;
    #    rewrite ^/.well-known/host-meta /public.php?service=host-meta last;
    #    rewrite ^/.well-known/host-meta.json /public.php?service=host-meta-json;
    #    location = /.well-known/carddav {
    #      return 301 $scheme://$host/remote.php/dav;
    #    }
    #    location = /.well-known/caldav {
    #      return 301 $scheme://$host/remote.php/dav;
    #    }
    #    location = /robots.txt {
    #      allow all;
    #      log_not_found off;
    #      access_log off;
    #    }
    #    location ~ ^/(?:build|tests|config|lib|3rdparty|templates|data)/ {
    #      deny all;
    #    }
    #    location ~ ^/(?:autotest|occ|issue|indie|db_|console) {
    #      deny all;
    #    }
    # tls:
    #   - secretName: nextcloud-tls
    #     hosts:
    #       - nextcloud.kube.home
    labels: {}
    path: /
    pathType: Prefix
